# Generated by Django 4.1.5 on 2023-01-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
