# Generated by Django 4.1.5 on 2023-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_tags_article_tags_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='articles_set', through='webapp.ArticleTag', to='webapp.tag'),
        ),
    ]
